### ISSUE TITLE
Unable to see Dapr enabled services in Application Insights. 

### ISSUE THREAD

**Issue by Phiph** [Azure-Samples/container-apps-store-api-microservice#11]
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Unable to see Telemetry in Application Insights. 

In my own repo, that's using the workflow and Bicep files provided here (Thank you, life saver) I can't seem to get my services to show in Application Insights. 

I'm using Dapr in all my services. 

### Mention any other details that might be useful
I've made some modifications to the bicep, but all seems okay. 

This is just a request to see if it's still working your end :) Just incase API's or something has changed already :) 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by tetsuyasodo** [comment]
I have the same problem. As I confirmed the doc (*1), the latest bicep template format doesn't allow the "daprAIInstrumentationKey" property in L.45 of deploy/environment.bicep file in this repo.

>      daprAIInstrumentationKey: appInsights.properties.InstrumentationKey

(*1) https://docs.microsoft.com/en-us/azure/templates/microsoft.web/kubeenvironments?tabs=bicep

I'd like to know whether this is document bug or bicep/ARMTemplate bug?

**Comment by jeffhollan** [comment]
Yes there was a bug that was filed and is rolling out to fix this. I'll work to get latest update from team and close once someone confirms the fix is live

**Comment by Phiph** [comment]
Thank you @jeffhollan!
