### ISSUE TITLE
Bicep deploy fails for ContainerApp image name

### ISSUE THREAD

**Issue by jimlane** [Azure-Samples/container-apps-store-api-microservice#27]
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
- Fork repository
- Set environment variables
- Invoke workflow
- Receive error msg

### Any log messages given by the failure
> ERROR: ***"code": "InvalidTemplateDeployment", "message": "The template deployment 'main' is not valid according to the validation procedure. The tracking id is 'af20d38b-10[53](https://github.com/jimlane/container-apps-store-api-microservice/runs/7773620294?check_suite_focus=true#step:4:54)-41f9-8b24-2a7b70cf[54](https://github.com/jimlane/container-apps-store-api-microservice/runs/7773620294?check_suite_focus=true#step:4:55)c2'. See inner errors for details."***

> Inner Errors: 
***"code": "ValidationForMultipleResourcesFailed", "message": "Validation failed for multiple resources. Check 'Error.Details[]' for more information."***

> Inner Errors: 
***"code": "ContainerAppImageRequired", "message": "Container with name 'python-app' must have an 'Image' property specified."***

> Inner Errors: 
***"code": "ContainerAppImageRequired", "message": "Container with name 'go-app' must have an 'Image' property specified."***

> Inner Errors: 
***"code": "ContainerAppImageRequired", "message": "Container with name 'node-app' must have an 'Image' property specified."***
Error: Error: az cli script failed.

### Expected/desired behavior
> Deployment succeeds

### OS and Version?
> Ubuntu 20.04.4
>Runner Version: 2.294.0

**Comment by kendallroden** [comment]
Thanks for this. I ran into this in another sample and solved it so I will update this one accordingly in the next few min @jimlane

**Comment by kendallroden** [comment]
confirmed fix
