### ISSUE TITLE
Cchanging the deployment from canadacentral to useast makes it fail

### ISSUE THREAD

**Issue by chanezon** [Azure-Samples/container-apps-store-api-microservice#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> changing the deployment from canadacentral to useast makes it fail. Is the servie available only in canadacentral for now?
https://github.com/chanezon/container-apps-store-api-microservice/commit/8b2bec8a820de8612aa24d6b7d0a44c210535c05

### Any log messages given by the failure
>
ERROR: ***"status":"Failed","error":***"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[***"code":"Conflict","message":"***\r\n  \"status\": \"Failed\",\r\n  \"error\": ***\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      ***\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          ***\r\n            \"code\": \"Conflict\",\r\n            \"message\": \"***\\r\\n  \\\"error\\\": ***\\r\\n    \\\"code\\\": \\\"MissingSubscriptionRegistration\\\",\\r\\n    \\\"message\\\": \\\"The subscription is not registered to use namespace 'Microsoft.OperationalInsights'. See https://aka.ms/rps-not-found for how to register subscriptions.\\\",\\r\\n    \\\"details\\\": [\\r\\n      ***\\r\\n        \\\"code\\\": \\\"MissingSubscriptionRegistration\\\",\\r\\n        \\\"target\\\": \\\"Microsoft.OperationalInsights\\\",\\r\\n        \\\"message\\\": \\\"The subscription is not registered to use namespace 'Microsoft.OperationalInsights'. See https://aka.ms/rps-not-found for how to register subscriptions.\\\"\\r\\n      ***\\r\\n    ]\\r\\n  ***\\r\\n***\"\r\n          ***,\r\n          ***\r\n            \"code\": \"Conflict\",\r\n            \"message\": \"***\\r\\n  \\\"error\\\": ***\\r\\n    \\\"code\\\": \\\"MissingSubscriptionRegistration\\\",\\r\\n    \\\"message\\\": \\\"The subscription is not registered to use namespace 'microsoft.insights'. See https://aka.ms/rps-not-found for how to register subscriptions.\\\",\\r\\n    \\\"details\\\": [\\r\\n      ***\\r\\n        \\\"code\\\": \\\"MissingSubscriptionRegistration\\\",\\r\\n        \\\"target\\\": \\\"microsoft.insights\\\",\\r\\n        \\\"message\\\": \\\"The subscription is not registered to use namespace 'microsoft.insights'. See https://aka.ms/rps-not-found for how to register subscriptions.\\\"\\r\\n      ***\\r\\n    ]\\r\\n  ***\\r\\n***\"\r\n          ***\r\n        ]\r\n      ***\r\n    ]\r\n  ***\r\n***"***,***"code":"Conflict","message":"***\r\n  \"status\": \"Failed\",\r\n  \"error\": ***\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      ***\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          ***\r\n            \"code\": \"Conflict\",\r\n            \"message\": \"***\\r\\n  \\\"error\\\": ***\\r\\n    \\\"code\\\": \\\"MissingSubscriptionRegistration\\\",\\r\\n    \\\"message\\\": \\\"The subscription is not registered to use namespace 'Microsoft.ApiManagement'. See https://aka.ms/rps-not-found for how to register subscriptions.\\\",\\r\\n    \\\"details\\\": [\\r\\n      ***\\r\\n        \\\"code\\\": \\\"MissingSubscriptionRegistration\\\",\\r\\n        \\\"target\\\": \\\"Microsoft.ApiManagement\\\",\\r\\n        \\\"message\\\": \\\"The subscription is not registered to use namespace 'Microsoft.ApiManagement'. See https://aka.ms/rps-not-found for how to register subscriptions.\\\"\\r\\n      ***\\r\\n    ]\\r\\n  ***\\r\\n***\"\r\n          ***\r\n        ]\r\n      ***\r\n    ]\r\n  ***\r\n***"***]***

### Expected/desired behavior
> Not a big deal, but if the service is only available in certain regions it may be worth mentioning it in the README

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by thepaulmacca** [comment]
It's only available in Canada Central and North Europe at the moment
