### ISSUE TITLE
Missing or invalid type information in bicep

### ISSUE THREAD

**Issue by takekazuomi** [Azure-Samples/container-apps-store-api-microservice#7]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

```
cd deploy
az bicep build --file main.bicep
```

### Any log messages given by the failure

- container-http.bicep(32,23) : Warning BCP081: Resource type "Microsoft.Web/containerApps@2021-03-01" does not have types available.
- environment.bicep(26,16) : Warning BCP036: The property "Flow_Type" expected a value of type "'Bluefield' | null" but the provided value is of type "'Redfield'".
- environment.bicep(27,21) : Warning BCP036: The property "Request_Source" expected a value of type "'rest' | null" but the provided value is of type "'CustomDeployment'".
- environment.bicep(35,5) : Warning BCP037: The property "type" is not allowed on objects of type "KubeEnvironmentProperties". Permissible properties include "aksResourceID", "arcConfiguration", "staticIp". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
- environment.bicep(44,5) : Warning BCP037: The property "containerAppsConfiguration" is not allowed on objects of type "KubeEnvironmentProperties". Permissible properties include "aksResourceID", "arcConfiguration", "staticIp". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]

### Expected/desired behavior

-There is no documentation for "Microsoft.Web/containerApps".
-"Microsoft.Web/kubeEnvironments" does not mention "type" and "containerAppsConfiguration".
https://docs.microsoft.com/en-us/azure/templates/microsoft.web/kubeenvironments?tabs=bicep

### Versions

Bicep CLI version 0.4.1008

### Mention any other details that might be useful

https://github.com/Azure/bicep/issues/784#issuecomment-959799594
https://github.com/Azure/bicep/issues/784#issuecomment-959805535

**Comment by thepaulmacca** [comment]
I was wondering this earlier - I usually check the REST API specs, but that's not been updated yet https://github.com/Azure/azure-rest-api-specs/tree/main/specification/web/resource-manager/Microsoft.Web/stable

**Comment by jeffhollan** [comment]
Correct - we're working on publishing the api specs and once those are available these warnings should go away

**Comment by takekazuomi** [comment]
I got response from bicep team. We seem to have to wait a bit. But it works, so I have no problem.
https://github.com/Azure/bicep/issues/784#issuecomment-963529983

**Comment by takekazuomi** [comment]
FIXED
https://github.com/Azure/bicep/releases/tag/v0.4.1272
